#!/bin/sh

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
  start)
  exec forever --sourceDir=/opt/rpi_app/deploy -p /var/run/forever start model/app.js
  ;;

  stop)
  exec forever stop --sourceDir=/rpi_app/deploy model/app.js
  ;;
esac

exit 0
